global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'http_.*'
        action: keep
      - source_labels: [__name__]
        regex: 'fastapi_.*'
        action: keep
      - source_labels: [__name__]
        regex: 'sqlalchemy_.*'
        action: keep
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'fastapi-app'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'prometheus_.*'
        action: keep 